<div class="container">
    <h1 class="text-center text-primary">Create new playlist</h1>
    <form method="POST" class="w-50 m-auto mt-5">
        <div class="form-floating mb-3">
            <input type="text" class="form-control" name="name" placeholder="name">
            <label for="name">Name</label>
        </div>
        <div class="form-floating mt-2">
            <input type="text" class="form-control" name="description" placeholder="Discription">
            <label for="description">Description</label>
        </div>
        <div class="mt-3">
            <label for="public">Visibility</label>
            <select name="public" class="form-select" aria-label="Default select example">
                <option value="true">Public</option>
                <option value="false">Private</option>
            </select>
        </div>
        <button class="btn btn-primary mt-3" type="submit">Add playlist</button>
    </form>
</div>