<div class="">
    <h1 class="text-center text-primary">Search any song, albums, playlist</h1>
    <hr>
    <form class="mt-3" method="POST">
        <div class="m-auto text-center w-50 ">
            <input class="form-control w-50 d-inline" name='search'>
            <button type="submit" class="btn btn-success mx-2">Search</button>
        </div>
        <div class="mt-5 w-75 m-auto">
            <h4 class="text-primary d-inline mx-5">Select filters</h4>
            <div class="form-check form-check-inline">
                <input class="form-check-input" name="filters[]" type="checkbox" id="inlineCheckbox1" value="album">
                <label class="form-check-label" for="inlineCheckbox1">Album</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" name="filters[]" type="checkbox" id="inlineCheckbox2" value="artist">
                <label class="form-check-label" for="inlineCheckbox2">Artist</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" name="filters[]" type="checkbox" id="inlineCheckbox3" value="playlist">
                <label class="form-check-label" for="inlineCheckbox3">Playlist</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" name="filters[]" type="checkbox" id="inlineCheckbox3" value="track">
                <label class="form-check-label" for="inlineCheckbox3">Track</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" name="filters[]" type="checkbox" id="inlineCheckbox3" value="show">
                <label class="form-check-label" for="inlineCheckbox3">Show</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" name="filters[]" type="checkbox" id="inlineCheckbox3" value="episode">
                <label class="form-check-label" for="inlineCheckbox3">Episode</label>
            </div>
        </div>
    </form>
</div>
<hr>
<div class="container">
    <?php
    if (isset($details)) {
        foreach ($details as $key => $val) {
            $html='<hr>';
            $html .= '<div id="#'.$key.'" class="row mt-3 text-start">
                    <h3 class="text-info text-center">'.ucwords($key).'</h3>';
            foreach ($val['items'] as $v) {
                $html .= '<div class="col mt-3">
                    <div class="card shadow" style="width: 22rem;">';
                    if (isset($v['images'])) {
                        $html .= '<img src="'.$v['images'][0]['url'].'" class="card-img-top border" alt="'.$v['name'].'" height="300px">';
                    }
                    $html .='<div class="card-body">
                            <h5 class="card-title">' . $v['name'] . '</h5>';
                    if($key=='tracks') {
                        $html .= '<p>Artist:  &nbsp;'.$v['artists'][0]['name'].'</p>
                                <audio controls><source src="' . $v['preview_url'] . '" type="audio/mpeg"> </audio>
                                <a class="btn btn-sm btn-success" href="'.$v['external_urls']['spotify'].'">Play on spotify</a>
                                <a href="/index/addtoplaylist/'.$v['id'].'" class="btn btn-sm btn-success mx-3">Add to playlist +</a>';
                    }
                    $html .= '</div>
                    </div>
                </div>';
            }
            echo $html.'</div>';
        }
    }
    
    ?>
</div>
