<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Spotify-App</title>
    <link rel="stylesheet" href="/assets/node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <style>
        .login-icon{
            font-size: 80px;
            color: #0B5ED7;
        }
    </style>
    </style>
</head>

<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand text-success" href="/">Spotify</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/users/login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/playlist/create">Create playlist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/playlist">My playlists</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <?php echo $this->getContent(); ?>
    </div>
    <script src="/assets/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
</body>

</html>